[dev]
  command = "npm start" # Command to start your dev server
  targetPort = 3000 # # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "https://splitexpense.tanmaydatta.workers.dev/.netlify/functions/:splat"
  status = 200
  force = true