name = "splitexpense"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "https://splitexpense.netlify.app,https://deploy-preview-5--splitexpense.netlify.app,http://localhost:3000,http://localhost:3001"
GROUP_IDS = "1"

[[d1_databases]]
binding = "DB"
database_name = "splitexpense-dev"
database_id = "a721ee7e-a5ee-452d-88d4-ebb97a1f0786" 
#binding = "DB"
#database_name = "splitexpense"
#database_id = "56f19864-f964-4c28-b176-001047d58e00" 

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



[triggers]
crons = [ "0 0 1 * *" ]

[env.prod]
    [[env.prod.d1_databases]]
    binding = "DB"
    database_name = "splitexpense"
    database_id = "56f19864-f964-4c28-b176-001047d58e00" 

    [env.prod.vars]
    ALLOWED_ORIGINS = "https://splitexpense.netlify.app,https://deploy-preview-5--splitexpense.netlify.app,http://localhost:3000,http://localhost:3001"
    GROUP_IDS = "1"



[env.dev]
    [[env.dev.d1_databases]]
    binding = "DB"
    database_name = "splitexpense-dev"
    database_id = "a721ee7e-a5ee-452d-88d4-ebb97a1f0786" 

    [env.dev.vars]
    ALLOWED_ORIGINS = "https://staging--splitexpense.netlify.app,https://splitexpense.netlify.app,https://deploy-preview-5--splitexpense.netlify.app,http://localhost:3000,http://localhost:3001"
    GROUP_IDS = "1"
