name = "splitexpense"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Workflows configuration
[[workflows]]
binding = "ORCHESTRATOR_WORKFLOW"
class_name = "ScheduledActionsOrchestratorWorkflow"
name = "scheduled-actions-orchestrator"

[[workflows]]
binding = "PROCESSOR_WORKFLOW"
class_name = "ScheduledActionsProcessorWorkflow"
name = "scheduled-actions-processor"

# Static assets configuration for Single Page Application
[assets]
directory = "../build"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/.netlify/functions/*", "/hello", "/auth/*"]

[vars]
ALLOWED_ORIGINS = "https://staging--splitexpense.netlify.app,https://splitexpense.netlify.app,https://deploy-preview-5--splitexpense.netlify.app,http://localhost:3000,http://localhost:3001"
GROUP_IDS = ""
BASE_URL = "http://localhost:8787/auth"
AUTH_TRUSTED_ORIGINS = ["http://localhost:8787", "http://localhost:3000"]
LOCAL = true

[[d1_databases]]
binding = "DB"
database_name = "splitexpense-dev"
database_id = "a721ee7e-a5ee-452d-88d4-ebb97a1f0786" 
migrations_dir = "src/db/migrations"
#binding = "DB"
#database_name = "splitexpense"
#database_id = "56f19864-f964-4c28-b176-001047d58e00" 

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



#[triggers]
#crons = [ "0 0 * * *" ]  # Daily at midnight UTC for scheduled actions

[env.prod]
    [[env.prod.d1_databases]]
    binding = "DB"
    database_name = "splitexpense"
    database_id = "56f19864-f964-4c28-b176-001047d58e00" 
    migrations_dir = "src/db/migrations"
    
    [env.prod.vars]
    ALLOWED_ORIGINS = "https://splitexpense.netlify.app,https://deploy-preview-5--splitexpense.netlify.app,http://localhost:3000,http://localhost:3001"
    GROUP_IDS = ""
    BASE_URL = "https://splitexpense.tanmaydatta.workers.dev/auth"
    AUTH_TRUSTED_ORIGINS = ["https://splitexpense.tanmaydatta.workers.dev"]
    LOCAL = false

    [[env.prod.workflows]]
    binding = "ORCHESTRATOR_WORKFLOW"
    class_name = "ScheduledActionsOrchestratorWorkflow"
    name = "scheduled-actions-orchestrator"

    [[env.prod.workflows]]
    binding = "PROCESSOR_WORKFLOW"
    class_name = "ScheduledActionsProcessorWorkflow"
    name = "scheduled-actions-processor"



[env.dev]
    [[env.dev.d1_databases]]
    binding = "DB"
    database_name = "splitexpense-dev"
    database_id = "a721ee7e-a5ee-452d-88d4-ebb97a1f0786"
    migrations_dir = "src/db/migrations"

    [env.dev.vars]
    ALLOWED_ORIGINS = "https://splitexpense-dev.tanmaydatta.workers.dev,https://splitexpense.netlify.app,https://deploy-preview-5--splitexpense.netlify.app,http://localhost:3000,http://localhost:3001"
    GROUP_IDS = ""
    BASE_URL = "https://splitexpense-dev.tanmaydatta.workers.dev/auth"
    AUTH_TRUSTED_ORIGINS = ["https://splitexpense-dev.tanmaydatta.workers.dev"]
    LOCAL = false

    [[env.dev.workflows]]
    binding = "ORCHESTRATOR_WORKFLOW"
    class_name = "ScheduledActionsOrchestratorWorkflow"
    name = "scheduled-actions-orchestrator-dev"

    [[env.dev.workflows]]
    binding = "PROCESSOR_WORKFLOW"
    class_name = "ScheduledActionsProcessorWorkflow"
    name = "scheduled-actions-processor-dev"

