name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  lint-react:
    name: Lint React App
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Run React linting
      run: yarn lint

  lint-cf-worker:
    name: Lint CF Worker
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: 'cf-worker/yarn.lock'
    
    - name: Install CF Worker dependencies
      run: |
        cd cf-worker
        yarn install --immutable
    
    - name: Run CF Worker linting
      run: |
        cd cf-worker
        yarn lint

  test-cf-worker:
    name: Test CF Worker
    runs-on: ubuntu-latest
    needs: lint-cf-worker
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    
    - name: Install main app dependencies
      run: yarn install --immutable
    
    - name: Build UI for CF Worker tests
      run: yarn build
    
    - name: Install CF Worker dependencies
      run: |
        cd cf-worker
        yarn install --immutable
    
    - name: Run CF Worker tests
      run: |
        cd cf-worker
        yarn test 