name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # Job-level environment variables (available to all steps)
    env:
      REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
      AUTH_PIN: ${{ secrets.AUTH_PIN }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Install cf-worker dependencies
      run: |
        cd cf-worker
        yarn install --immutable
    
    - name: Install Playwright Browsers and System Dependencies
      run: yarn test:e2e:install
    
    - name: Build the application
      run: yarn build
    
    - name: Setup local database
      run: |
        cd cf-worker
        # Execute the database schema setup
        yarn wrangler d1 execute splitexpense-dev --local --file=dev-schema.sql
        echo "Database schema setup completed!"
    
    - name: Start cf-worker locally
      run: |
        cd cf-worker
        yarn dev &
        echo "Waiting for cf-worker to start..."
        sleep 10
        # Wait for cf-worker to be ready (check if port 8787 is responding)
        timeout 30 bash -c 'until curl -f http://localhost:8787/hello > /dev/null 2>&1; do sleep 2; done'
        echo "cf-worker is ready!"
      env:
        AUTH_PIN: ${{ secrets.AUTH_PIN }}
    
    - name: Run E2E tests
      run: yarn test:e2e --workers=1 --reporter=list,html --trace=on
      env:
        AUTH_PIN: ${{ secrets.AUTH_PIN }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-screenshots
        path: test-results/
        retention-days: 7 